"""
Temporal (mid-rollout) perturbation engine for LIBERO/MuJoCo environments.

This module does not generate BDDL or sample perturbation coordinates. It consumes
temporal_perturbations from the record config (generated by the pipeline's random_design
or by hand) and applies/reverts each perturbation at the configured start_step and
end_step during the rollout.

Perturbations are defined as time-windowed specs with [start_step, end_step].
At start_step, the perturbation is applied directly to the live MuJoCo sim.
At end_step, the original state is restored (revert=True by default).

Timing conventions (for config/main.yaml):
  - Full duration of rollout: set start_step to 0 (first frame) and end_step to
    FULL_ROLLOUT_END_STEP (or any value >= episode length) so the perturbation
    is never reverted during the episode.
  - Exact timestep window: set start_step and end_step to the desired frame
    range; at end_step+1 the state is reverted.

Supported perturbation types (all applied via sim state manipulation):
  - move      : Teleport object to a new XY position in the table plane
  - color     : Change object geom RGBA color(s)
  - distractor: Teleport a pre-loaded "hidden" object into the scene
  - replace   : Hide original object off-screen, teleport replacement in

Architecture notes:
  - MuJoCo does NOT support adding new bodies mid-episode, so distractors and
    replacement objects must be declared in the BDDL and pre-spawned far
    off-screen (via a special helper BDDL writer), then teleported in/out.
  - Object positions are set via free-joint qpos (7-DOF: xyz + quaternion).
  - Colors are set via sim.model.geom_rgba (Nx4 float32 array).
  - All original state is snapshotted just before a perturbation window opens
    and fully restored when the window closes — UNLESS the robot gripper moved
    the object during the perturbation window, in which case the position revert
    is skipped so the object remains where the robot left it.

Robot-movement detection:
  - At start_step, alongside the original pose, we also record the
    perturbation-applied pose (i.e. the pose we explicitly wrote to the sim).
  - At end_step + 1, we read the object's current pose and compare it to the
    perturbation-applied pose using a configurable 3-D (XYZ) distance threshold
    (default: ROBOT_MOVE_THRESHOLD_M = 0.0 m, i.e. any movement counts).
  - If the current pose differs from the perturbation-applied pose by more than
    the threshold, we infer that the robot gripper moved the object during the
    window and skip restoring that object's position (while still reverting
    colors as normal).  This applies to ALL object types including distractors.

Collision detection & resolution:
  - All perturbations only move objects in the XY table plane.  Z is never
    changed by the perturbation itself.
  - Before placing an object the engine checks every other scene object for XY
    overlap (distance < sum of approximate radii derived from geom sizes).
  - Special case — open articulated cavities (drawers, cabinet doors):
      If a fixture body whose articulated joint is open (angle > OPEN_JOINT_THRESHOLD_RAD)
      overlaps the target XY, the perturbed object is placed INSIDE that cavity
      (at the cavity's XY centre and Z centre) rather than on the table surface.
      This correctly handles e.g. an open drawer that a plate would otherwise
      clip into — the plate is placed in the drawer.
  - If NO open cavity matches but plain object collisions exist, the perturbed
    object is stacked on top of the highest collider:
        z_final = collider_z + collider_half_height + perturbed_half_height + Z_STACK_GAP_M
    where Z_STACK_GAP_M is a tiny buffer (default 2 mm) so objects don't clip.
  - If there are no collisions the original Z is preserved unchanged.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from typing import Any, Dict, List, Optional, Tuple

import numpy as np

# ---------------------------------------------------------------------------
# Off-screen "parking" position for hidden objects
# ---------------------------------------------------------------------------
_OFFSCREEN_XYZ = np.array([100.0, 100.0, 100.0], dtype=np.float64)
_IDENTITY_QUAT = np.array([1.0, 0.0, 0.0, 0.0], dtype=np.float64)

# Sentinel end_step for "full rollout": perturbation from first frame until episode end.
# Use in config: end_step: 99999 (or this constant's value) with start_step: 0.
FULL_ROLLOUT_END_STEP: int = 99999

# ---------------------------------------------------------------------------
# Robot-movement detection threshold (metres, full 3-D XYZ distance).
# ---------------------------------------------------------------------------
ROBOT_MOVE_THRESHOLD_M: float = 0.0

# ---------------------------------------------------------------------------
# Collision resolution constants
# ---------------------------------------------------------------------------

# Small vertical buffer (m) added between the stacked objects so they do not
# clip through each other.  This is the ONLY Z adjustment made — it is purely
# a physics separation buffer, not a configurable perturbation dimension.
Z_STACK_GAP_M: float = 0.002  # 2 mm

# A hinge/slide joint whose position (radians or metres) exceeds this value is
# treated as "open" for the purposes of the drawer-placement heuristic.
OPEN_JOINT_THRESHOLD_RAD: float = 0.05

# Default color palette for color perturbations
COLOR_PALETTE: Dict[str, np.ndarray] = {
    "red":     np.array([1.0, 0.0, 0.0, 1.0], dtype=np.float32),
    "blue":    np.array([0.0, 0.0, 1.0, 1.0], dtype=np.float32),
    "green":   np.array([0.0, 1.0, 0.0, 1.0], dtype=np.float32),
    "yellow":  np.array([1.0, 1.0, 0.0, 1.0], dtype=np.float32),
    "purple":  np.array([0.5, 0.0, 0.5, 1.0], dtype=np.float32),
    "orange":  np.array([1.0, 0.5, 0.0, 1.0], dtype=np.float32),
    "cyan":    np.array([0.0, 1.0, 1.0, 1.0], dtype=np.float32),
    "magenta": np.array([1.0, 0.0, 1.0, 1.0], dtype=np.float32),
    "white":   np.array([1.0, 1.0, 1.0, 1.0], dtype=np.float32),
    "black":   np.array([0.0, 0.0, 0.0, 1.0], dtype=np.float32),
}


# ---------------------------------------------------------------------------
# Low-level MuJoCo helpers
# ---------------------------------------------------------------------------

def _get_body_id(sim, body_name: str) -> int:
    try:
        return sim.model.body_name2id(body_name)
    except Exception:
        return -1


def _get_joint_id(sim, joint_name: str) -> int:
    try:
        return sim.model.joint_name2id(joint_name)
    except Exception:
        return -1


def _get_geom_ids_for_body(sim, body_id: int) -> List[int]:
    return [g for g in range(sim.model.ngeom) if sim.model.geom_bodyid[g] == body_id]


def _find_object_body_name(sim, obj_name: str) -> Optional[str]:
    for candidate in (obj_name, f"{obj_name}_main", f"{obj_name}_base", f"{obj_name}_body"):
        if _get_body_id(sim, candidate) >= 0:
            return candidate
    for i in range(sim.model.nbody):
        bname = sim.model.body_id2name(i)
        if obj_name in bname:
            return bname
    return None


def _get_free_joint_qpos_addr(sim, obj_name: str) -> Optional[Tuple[int, str]]:
    for jname in (f"{obj_name}_joint0", f"{obj_name}_freejoint", f"{obj_name}:joint", obj_name):
        jid = _get_joint_id(sim, jname)
        if jid >= 0 and sim.model.jnt_type[jid] == 0:
            return sim.model.jnt_qposadr[jid], jname
    for jid in range(sim.model.njnt):
        jname = sim.model.joint_id2name(jid)
        if obj_name in jname and sim.model.jnt_type[jid] == 0:
            return sim.model.jnt_qposadr[jid], jname
    return None


def _read_object_pose(sim, obj_name: str) -> Optional[np.ndarray]:
    result = _get_free_joint_qpos_addr(sim, obj_name)
    if result is None:
        return None
    addr, _ = result
    return sim.data.qpos[addr: addr + 7].copy()


def _write_object_pose(sim, obj_name: str, pose: np.ndarray) -> bool:
    result = _get_free_joint_qpos_addr(sim, obj_name)
    if result is None:
        print(f"[TEMPORAL] WARN: No free joint found for '{obj_name}'. Cannot set pose.")
        return False
    addr, jname = result
    sim.data.qpos[addr: addr + 7] = pose
    vel_addr = sim.model.jnt_dofadr[sim.model.joint_name2id(jname)]
    sim.data.qvel[vel_addr: vel_addr + 6] = 0.0
    sim.forward()
    return True


def _read_object_colors(sim, obj_name: str) -> Optional[Dict[int, np.ndarray]]:
    body_name = _find_object_body_name(sim, obj_name)
    if body_name is None:
        return None
    body_id = _get_body_id(sim, body_name)
    geom_ids = _get_geom_ids_for_body(sim, body_id)
    if not geom_ids:
        return None
    return {gid: sim.model.geom_rgba[gid].copy() for gid in geom_ids}


def _write_object_colors(sim, obj_name: str, rgba: np.ndarray) -> bool:
    body_name = _find_object_body_name(sim, obj_name)
    if body_name is None:
        print(f"[TEMPORAL] WARN: Body not found for '{obj_name}'. Cannot set color.")
        return False
    body_id = _get_body_id(sim, body_name)
    geom_ids = _get_geom_ids_for_body(sim, body_id)
    if not geom_ids:
        print(f"[TEMPORAL] WARN: No geoms found for '{obj_name}'. Cannot set color.")
        return False
    for gid in geom_ids:
        sim.model.geom_rgba[gid] = rgba
    return True


def _park_object(sim, obj_name: str) -> bool:
    return _write_object_pose(sim, obj_name, np.concatenate([_OFFSCREEN_XYZ, _IDENTITY_QUAT]))


def _place_object_at_xyz(sim, obj_name: str, x: float, y: float, z: float) -> bool:
    """
    Teleport an object to explicit (x, y, z) world coordinates.
    Preserves current quaternion orientation.
    """
    current_pose = _read_object_pose(sim, obj_name)
    quat = current_pose[3:7] if current_pose is not None else _IDENTITY_QUAT
    return _write_object_pose(sim, obj_name, np.array([x, y, z, *quat], dtype=np.float64))


# ---------------------------------------------------------------------------
# Geometry helpers — XY radius and Z half-height from geom sizes
# ---------------------------------------------------------------------------

def _geom_xy_radius(gtype: int, sz: np.ndarray) -> float:
    """Approximate XY footprint radius of a single geom."""
    # MuJoCo geom types: 2=sphere, 3=capsule, 4=ellipsoid, 5=cylinder, 6=box, 7=mesh
    if gtype == 2:   return float(sz[0])                          # sphere
    if gtype == 3:   return float(sz[0])                          # capsule radius
    if gtype == 5:   return float(sz[0])                          # cylinder radius
    if gtype == 6:   return float(np.sqrt(sz[0]**2 + sz[1]**2))  # box diagonal
    return float(np.max(sz[:3]))                                   # mesh / other


def _geom_z_half_height(gtype: int, sz: np.ndarray) -> float:
    """Approximate Z half-extent of a single geom (how tall above its centre)."""
    if gtype == 2:   return float(sz[0])           # sphere radius
    if gtype == 3:   return float(sz[0] + sz[1])   # capsule radius + half-length
    if gtype == 5:   return float(sz[1])            # cylinder half-length
    if gtype == 6:   return float(sz[2])            # box Z half-extent
    return float(np.max(sz[:3]))


def _object_xy_radius(sim, obj_name: str) -> float:
    body_name = _find_object_body_name(sim, obj_name)
    if body_name is None:
        return 0.05
    body_id = _get_body_id(sim, body_name)
    geom_ids = _get_geom_ids_for_body(sim, body_id)
    if not geom_ids:
        return 0.05
    return max((_geom_xy_radius(sim.model.geom_type[g], sim.model.geom_size[g])
                for g in geom_ids), default=0.05)


def _object_z_half_height(sim, obj_name: str) -> float:
    body_name = _find_object_body_name(sim, obj_name)
    if body_name is None:
        return 0.05
    body_id = _get_body_id(sim, body_name)
    geom_ids = _get_geom_ids_for_body(sim, body_id)
    if not geom_ids:
        return 0.05
    return max((_geom_z_half_height(sim.model.geom_type[g], sim.model.geom_size[g])
                for g in geom_ids), default=0.05)

def _get_all_fixture_bodies(sim, exclude_names=None):
    """
    Return body names of static fixtures (no free joint) that are
    actually present in the scene (not parked off-screen).
    Skips worldbody, robot links, and floor/ground planes.
    """
    exclude = set(exclude_names or [])
    
    # Collect body IDs that belong to free-jointed objects (already handled separately)
    free_jointed_body_ids = set()
    for jid in range(sim.model.njnt):
        if sim.model.jnt_type[jid] == 0:  # free joint
            free_jointed_body_ids.add(sim.model.jnt_bodyid[jid])

    fixtures = []
    for bid in range(1, sim.model.nbody):  # skip worldbody (0)
        bname = sim.model.body_id2name(bid)
        if bname in exclude:
            continue
        if bid in free_jointed_body_ids:
            continue
        # Skip robot links
        if any(x in bname.lower() for x in ("robot", "gripper", "finger", "hand", "arm")):
            continue
        # Skip floor/ground
        if any(x in bname.lower() for x in ("floor", "ground", "wall")):
            continue
        geom_ids = _get_geom_ids_for_body(sim, bid)
        if not geom_ids:
            continue
        fixtures.append(bname)
    return fixtures


def _fixture_xy_radius(sim, body_name):
    body_id = _get_body_id(sim, body_name)
    geom_ids = _get_geom_ids_for_body(sim, body_id)
    if not geom_ids:
        return 0.0
    return max(
        _geom_xy_radius(sim.model.geom_type[g], sim.model.geom_size[g])
        for g in geom_ids
    )


def _fixture_z_top(sim, body_name):
    """Return the world-frame Z of the topmost geom surface for a fixture body."""
    body_id = _get_body_id(sim, body_name)
    geom_ids = _get_geom_ids_for_body(sim, body_id)
    if not geom_ids:
        return 0.0
    tops = []
    for g in geom_ids:
        centre_z = sim.data.geom_xpos[g][2]
        half_h = _geom_z_half_height(sim.model.geom_type[g], sim.model.geom_size[g])
        tops.append(centre_z + half_h)
    return max(tops)


def _fixture_xy_centre(sim, body_name):
    """Return the world-frame XY centre of a fixture body (mean of geom centres)."""
    body_id = _get_body_id(sim, body_name)
    geom_ids = _get_geom_ids_for_body(sim, body_id)
    if not geom_ids:
        pos = sim.data.body_xpos[body_id]
        return float(pos[0]), float(pos[1])
    xs = [sim.data.geom_xpos[g][0] for g in geom_ids]
    ys = [sim.data.geom_xpos[g][1] for g in geom_ids]
    return float(np.mean(xs)), float(np.mean(ys))


# ---------------------------------------------------------------------------
# Scene object enumeration (movable, on-table objects only)
# ---------------------------------------------------------------------------

def _get_all_scene_objects(sim, exclude_names: Optional[List[str]] = None) -> List[str]:
    """
    Return names of all free-jointed (movable) objects currently on the table.
    Objects parked off-screen (|xyz| > 50 m) are excluded.
    """
    exclude = set(exclude_names or [])
    scene_objects: List[str] = []
    for jid in range(sim.model.njnt):
        if sim.model.jnt_type[jid] != 0:
            continue
        jname = sim.model.joint_id2name(jid)
        obj_name = jname
        for suffix in ("_joint0", "_freejoint", ":joint"):
            if obj_name.endswith(suffix):
                obj_name = obj_name[: -len(suffix)]
                break
        if obj_name in exclude:
            continue
        addr = sim.model.jnt_qposadr[jid]
        if np.max(np.abs(sim.data.qpos[addr: addr + 3])) > 50.0:
            continue
        scene_objects.append(obj_name)
    return scene_objects


# ---------------------------------------------------------------------------
# Open articulated cavity detection (drawers, cabinet doors)
# ---------------------------------------------------------------------------

@dataclass
class _CavityInfo:
    """Describes an open articulated cavity (drawer/door) in the scene."""
    body_name: str          # MuJoCo body name of the cavity interior
    centre_xyz: np.ndarray  # World-frame XYZ centre of the cavity (3,)
    xy_radius: float        # Approximate XY radius of the cavity opening
    z_half: float           # Half-height of the cavity interior


def _find_open_cavities(sim) -> List[_CavityInfo]:
    """
    Scan all non-free (hinge/slide) joints in the sim for articulated bodies
    that are currently open (joint position > OPEN_JOINT_THRESHOLD_RAD).

    For each open joint, compute the world-frame AABB of all geoms attached to
    that body and return a _CavityInfo describing the accessible interior volume.

    This handles open drawers and open cabinet doors generically.
    """
    cavities: List[_CavityInfo] = []

    for jid in range(sim.model.njnt):
        jtype = sim.model.jnt_type[jid]
        # Type 1 = hinge, type 2 = slide
        if jtype not in (1, 2):
            continue

        qpos_addr = sim.model.jnt_qposadr[jid]
        joint_pos = sim.data.qpos[qpos_addr]

        if abs(joint_pos) <= OPEN_JOINT_THRESHOLD_RAD:
            continue

        # The body that moves when this joint opens
        body_id = sim.model.jnt_bodyid[jid]
        body_name = sim.model.body_id2name(body_id)
        geom_ids = _get_geom_ids_for_body(sim, body_id)
        if not geom_ids:
            continue

        # Compute world-frame positions of all geom centres for this body
        geom_positions = []
        for gid in geom_ids:
            # sim.data.geom_xpos gives world position of each geom centre
            geom_positions.append(sim.data.geom_xpos[gid].copy())

        if not geom_positions:
            continue

        positions = np.array(geom_positions)
        centre_xyz = positions.mean(axis=0)

        # XY radius: max distance of any geom centre from the body XY centre
        xy_dists = np.sqrt((positions[:, 0] - centre_xyz[0])**2
                           + (positions[:, 1] - centre_xyz[1])**2)
        # Add the radius of the largest geom as a buffer
        geom_radii = [_geom_xy_radius(sim.model.geom_type[g], sim.model.geom_size[g])
                      for g in geom_ids]
        xy_radius = float(np.max(xy_dists) + np.max(geom_radii))

        # Z half-height: half the total span of geom centres in Z
        z_half = float((positions[:, 2].max() - positions[:, 2].min()) / 2 + 0.01)

        cavities.append(_CavityInfo(
            body_name=body_name,
            centre_xyz=centre_xyz,
            xy_radius=xy_radius,
            z_half=z_half,
        ))

    return cavities


# ---------------------------------------------------------------------------
# Core collision resolution
# ---------------------------------------------------------------------------

def _resolve_placement(
    sim,
    perturbed_obj: str,
    target_x: float,
    target_y: float,
    original_z: float,
) -> Tuple[float, float, float, str]:
    perturbed_radius = _object_xy_radius(sim, perturbed_obj)
    perturbed_z_half = _object_z_half_height(sim, perturbed_obj)

    # ------------------------------------------------------------------
    # 1. Static fixture collision check
    #    If the overlapping fixture is an open cavity, place INSIDE.
    #    Otherwise stack ON TOP.
    # ------------------------------------------------------------------
    open_cavities = _find_open_cavities(sim)
    open_cavity_body_names = {c.body_name: c for c in open_cavities}

    fixture_names = _get_all_fixture_bodies(sim, exclude_names=[perturbed_obj])
    fixture_colliders: List[str] = []
    highest_fixture_top_z = original_z

    new_xyz_reason_updated_height = [target_x, target_y, original_z, "no_collision", False]

    for fname in fixture_names:
        fx, fy = _fixture_xy_centre(sim, fname)
        xy_dist = np.sqrt((target_x - fx)**2 + (target_y - fy)**2)
        other_radius = _fixture_xy_radius(sim, fname)
        if xy_dist < perturbed_radius + other_radius:
            # Check if this colliding fixture is an open cavity
            if fname in open_cavity_body_names:
                cavity = open_cavity_body_names[fname]
                cx, cy = cavity.centre_xyz[0], cavity.centre_xyz[1]
                final_z = float(cavity.centre_xyz[2])
                reason = f"placed_in_cavity:{fname}"
                print(f"[TEMPORAL] COLLISION: '{perturbed_obj}' overlaps open cavity "
                      f"'{fname}'. Placing inside at ({cx:.4f}, {cy:.4f}, {final_z:.4f}).")
                if (new_xyz_reason_updated_height[2] < final_z):
                    new_xyz_reason_updated_height = [cx, cy, final_z, reason, True]

            fixture_colliders.append(fname)
            top_z = _fixture_z_top(sim, fname)
            if top_z > highest_fixture_top_z:
                highest_fixture_top_z = top_z

    if fixture_colliders:
        final_z = highest_fixture_top_z + perturbed_z_half + Z_STACK_GAP_M
        reason = f"stacked_above_fixture:{','.join(fixture_colliders)}"
        print(f"[TEMPORAL] COLLISION: '{perturbed_obj}' overlaps fixture(s) {fixture_colliders} "
              f"at ({target_x:.4f}, {target_y:.4f}). Stacking → z={final_z:.4f} m.")
        if (new_xyz_reason_updated_height[2] < final_z):
            new_xyz_reason_updated_height = [target_x, target_y, final_z, reason, True]

    # ------------------------------------------------------------------
    # 2. Free-jointed object collision check
    # ------------------------------------------------------------------
    scene_objects = _get_all_scene_objects(sim, exclude_names=[perturbed_obj])
    obj_colliders: List[str] = []
    highest_obj_top_z = original_z

    for other in scene_objects:
        other_pose = _read_object_pose(sim, other)
        if other_pose is None:
            continue
        xy_dist = np.sqrt((target_x - other_pose[0])**2 + (target_y - other_pose[1])**2)
        other_radius = _object_xy_radius(sim, other)
        if xy_dist < perturbed_radius + other_radius:
            obj_colliders.append(other)
            other_z_half = _object_z_half_height(sim, other)
            top_z = other_pose[2] + other_z_half
            if top_z > highest_obj_top_z:
                highest_obj_top_z = top_z

    if obj_colliders:
        final_z = highest_obj_top_z + perturbed_z_half + Z_STACK_GAP_M
        reason = f"stacked_above:{','.join(obj_colliders)}"
        print(f"[TEMPORAL] COLLISION: '{perturbed_obj}' overlaps object(s) {obj_colliders} "
              f"at ({target_x:.4f}, {target_y:.4f}). Stacking → z={final_z:.4f} m.")
        if (new_xyz_reason_updated_height[2] < final_z):
            new_xyz_reason_updated_height = [target_x, target_y, final_z, reason, True]

    # ------------------------------------------------------------------
    # 3. No collision
    # ------------------------------------------------------------------
    return new_xyz_reason_updated_height[0], new_xyz_reason_updated_height[1], new_xyz_reason_updated_height[2]-0.1, new_xyz_reason_updated_height[3], new_xyz_reason_updated_height[4]


# ---------------------------------------------------------------------------
# Robot-movement detection
# ---------------------------------------------------------------------------

def _robot_moved_object(
    current_pose: Optional[np.ndarray],
    applied_pose: Optional[np.ndarray],
    threshold_m: float = ROBOT_MOVE_THRESHOLD_M,
) -> bool:
    if current_pose is None or applied_pose is None:
        return True
    return float(np.linalg.norm(current_pose[:3] - applied_pose[:3])) > threshold_m


# ---------------------------------------------------------------------------
# Perturbation spec
# ---------------------------------------------------------------------------

@dataclass
class TemporalPerturbationSpec:
    """
    Defines a single time-windowed perturbation.

    Fields
    ------
    pert_type   : "move" | "color" | "distractor" | "replace"
    start_step  : Episode step at which to apply the perturbation (inclusive).
    end_step    : Episode step at which to revert the perturbation (inclusive).
    obj_name    : Primary object to perturb (not needed for distractor).
    robot_move_threshold_m :
        3-D XYZ distance (m) threshold for robot-movement detection.
        Default 0.0 m — any positional change counts as robot movement.

    move-specific
    -------------
    delta_xy    : (dx, dy) shift in metres; if None sampled from ±max_move_m.
    max_move_m  : Maximum random shift magnitude when delta_xy is None.

    color-specific
    --------------
    color       : Color name from COLOR_PALETTE, or None for a random pick.

    distractor-specific
    -------------------
    distractor_obj_name : Pre-loaded distractor object name in sim.
    distractor_xy       : (x, y) table-plane coords; random if None.

    replace-specific
    ----------------
    replacement_obj_name : Pre-loaded replacement object name in sim.
    """
    pert_type: str
    start_step: int
    end_step: int

    obj_name: Optional[str] = None
    robot_move_threshold_m: float = ROBOT_MOVE_THRESHOLD_M

    # move
    delta_xy: Optional[Tuple[float, float]] = None
    max_move_m: float = 0.05

    # color
    color: Optional[str] = None

    # distractor
    distractor_obj_name: Optional[str] = None
    distractor_xy: Optional[Tuple[float, float]] = None

    # replace
    replacement_obj_name: Optional[str] = None

    def validate(self):
        assert self.end_step >= self.start_step
        assert self.pert_type in ("move", "color", "distractor", "replace"), \
            f"Unknown pert_type: {self.pert_type}"
        if self.pert_type in ("move", "color", "replace"):
            assert self.obj_name, f"obj_name required for pert_type='{self.pert_type}'"
        if self.pert_type == "distractor":
            assert self.distractor_obj_name, "distractor_obj_name required"
        if self.pert_type == "replace":
            assert self.replacement_obj_name, "replacement_obj_name required"
        if self.color is not None:
            assert self.color in COLOR_PALETTE, f"Unknown color '{self.color}'"


# ---------------------------------------------------------------------------
# Internal snapshot
# ---------------------------------------------------------------------------

@dataclass
class _PerturbationSnapshot:
    spec: TemporalPerturbationSpec
    original_poses: Dict[str, np.ndarray] = field(default_factory=dict)
    applied_poses: Dict[str, np.ndarray] = field(default_factory=dict)
    original_colors: Dict[str, Dict[int, np.ndarray]] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Manager
# ---------------------------------------------------------------------------

class TemporalPerturbationManager:
    """
    Manages time-windowed perturbations for a single episode rollout.

    Usage
    -----
        manager = TemporalPerturbationManager(specs)
        manager.reset(env)

        for step in range(max_steps):
            manager.step(env, step)
            obs, reward, done, _ = env.step(action)

        manager.summary()

    Collision resolution
    --------------------
    Before placing any object the engine calls _resolve_placement() which:

    1. Checks open articulated cavities (drawers/cabinet doors).  If the target
       XY overlaps an open cavity, the object is placed INSIDE it (e.g. a plate
       ends up in an open drawer rather than clipping through it or on top of
       the whole chest).

    2. Otherwise checks all other free-jointed scene objects.  If any overlap
       is found the perturbed object is stacked on top of the highest collider:
           z = collider_z + collider_half_height + perturbed_half_height + 2 mm gap

    3. If no collision, the object's original Z is preserved (perturbations are
       purely in the XY table plane).

    Robot-movement detection
    ------------------------
    The exact pose written at start_step is recorded.  At end_step+1 the
    current pose is compared; if the XYZ shift exceeds robot_move_threshold_m
    the position revert is skipped so the robot's work is not undone.
    """

    def __init__(self, specs: List[TemporalPerturbationSpec]):
        for s in specs:
            s.validate()
        self.specs = specs
        self._snapshots: Dict[int, _PerturbationSnapshot] = {}
        self._active: Dict[int, bool] = {}
        self._log: List[str] = []
        self._sim = None
        self.perturbation_collision: bool = False

    def reset(self, env):
        self._sim = self._get_sim(env)
        self._snapshots = {}
        self._active = {i: False for i in range(len(self.specs))}
        self._log = []

        if self._sim is None:
            print("[TEMPORAL] WARN: Could not access sim. Perturbations will be skipped.")
            return

        for spec in self.specs:
            if spec.pert_type == "distractor" and spec.distractor_obj_name:
                ok = _park_object(self._sim, spec.distractor_obj_name)
                print(f"[TEMPORAL] Parked distractor '{spec.distractor_obj_name}'"
                      + ("" if ok else " [FAILED]"))
            if spec.pert_type == "replace" and spec.replacement_obj_name:
                ok = _park_object(self._sim, spec.replacement_obj_name)
                print(f"[TEMPORAL] Parked replacement '{spec.replacement_obj_name}'"
                      + ("" if ok else " [FAILED]"))

    def step(self, env, step_idx: int):
        sim = self._sim
        self.perturbation_collision = False
        if sim is None:
            return
        for i, spec in enumerate(self.specs):
            if step_idx == spec.start_step and not self._active[i]:
                snap = self._apply(sim, i, spec)
                if snap is not None:
                    self._snapshots[i] = snap
                    self._active[i] = True
            elif step_idx == spec.end_step + 1 and self._active[i]:
                self._revert(sim, i)
                self._active[i] = False

    def flush(self, env):
        sim = self._sim
        if sim is None:
            return
        for i, active in list(self._active.items()):
            if active:
                self._revert(sim, i)
                self._active[i] = False

    def summary(self):
        print("\n" + "=" * 60)
        print("[TEMPORAL] Perturbation Summary")
        print("=" * 60)
        for msg in self._log or ["  (no perturbations were applied)"]:
            print(f"  {msg}")
        print("=" * 60 + "\n")

    # ------------------------------------------------------------------
    # Apply helpers
    # ------------------------------------------------------------------

    def _apply(self, sim, idx: int, spec: TemporalPerturbationSpec
               ) -> Optional[_PerturbationSnapshot]:
        snap = _PerturbationSnapshot(spec=spec)
        if spec.pert_type == "move":        return self._apply_move(sim, spec, snap)
        if spec.pert_type == "color":       return self._apply_color(sim, spec, snap)
        if spec.pert_type == "distractor":  return self._apply_distractor(sim, spec, snap)
        if spec.pert_type == "replace":     return self._apply_replace(sim, spec, snap)
        return None

    def _apply_move(self, sim, spec, snap) -> Optional[_PerturbationSnapshot]:
        original_pose = _read_object_pose(sim, spec.obj_name)
        if original_pose is None:
            print(f"[TEMPORAL] WARN: Cannot read pose for '{spec.obj_name}'. Skipping move.")
            return None
        snap.original_poses[spec.obj_name] = original_pose

        if spec.delta_xy is not None:
            dx, dy = spec.delta_xy
        else:
            dx = np.random.uniform(-spec.max_move_m, spec.max_move_m)
            dy = np.random.uniform(-spec.max_move_m, spec.max_move_m)

        target_x = original_pose[0] + dx
        target_y = original_pose[1] + dy

        final_x, final_y, final_z, reason, self.perturbation_collision = _resolve_placement(
            sim, spec.obj_name, target_x, target_y, original_pose[2])
        

        ok = _place_object_at_xyz(sim, spec.obj_name, final_x, final_y, final_z)
        if ok:
            snap.applied_poses[spec.obj_name] = _read_object_pose(sim, spec.obj_name)
            msg = (f"step {spec.start_step}: MOVE '{spec.obj_name}' "
                   f"Δ({dx:+.4f},{dy:+.4f}) m → ({final_x:.4f},{final_y:.4f},{final_z:.4f}) "
                   f"[{reason}] [reverts step {spec.end_step + 1}]")
            print(f"[TEMPORAL] {msg}")
            self._log.append(msg)
            return snap
        return None

    def _apply_color(self, sim, spec, snap) -> Optional[_PerturbationSnapshot]:
        original_colors = _read_object_colors(sim, spec.obj_name)
        if original_colors is None:
            print(f"[TEMPORAL] WARN: Cannot read colors for '{spec.obj_name}'. Skipping.")
            return None
        snap.original_colors[spec.obj_name] = original_colors

        color_name = spec.color or np.random.choice(list(COLOR_PALETTE.keys()))
        rgba = COLOR_PALETTE[color_name]
        ok = _write_object_colors(sim, spec.obj_name, rgba)
        if ok:
            msg = (f"step {spec.start_step}: COLOR '{spec.obj_name}' → {color_name} "
                   f"[reverts step {spec.end_step + 1}]")
            print(f"[TEMPORAL] {msg}")
            self._log.append(msg)
            return snap
        return None

    def _apply_distractor(self, sim, spec, snap) -> Optional[_PerturbationSnapshot]:
        dname = spec.distractor_obj_name
        snap.original_poses[dname] = np.concatenate([_OFFSCREEN_XYZ, _IDENTITY_QUAT])

        if spec.distractor_xy is not None:
            tx, ty = spec.distractor_xy
        else:
            tx = np.random.uniform(-0.2, 0.2)
            ty = np.random.uniform(-0.2, 0.2)

        # Default Z for a newly appearing object is just above the table surface.
        default_z = 0.02
        final_x, final_y, final_z, reason, self.perturbation_collision = _resolve_placement(
            sim, dname, tx, ty, default_z)
        ok = _place_object_at_xyz(sim, dname, final_x, final_y, final_z)
        if ok:
            snap.applied_poses[dname] = _read_object_pose(sim, dname)
            msg = (f"step {spec.start_step}: DISTRACTOR '{dname}' "
                   f"→ ({final_x:.4f},{final_y:.4f},{final_z:.4f}) "
                   f"[{reason}] [reverts step {spec.end_step + 1}]")
            print(f"[TEMPORAL] {msg}")
            self._log.append(msg)
            return snap
        return None

    def _apply_replace(self, sim, spec, snap) -> Optional[_PerturbationSnapshot]:
        original_pose = _read_object_pose(sim, spec.obj_name)
        if original_pose is None:
            print(f"[TEMPORAL] WARN: Cannot read pose for '{spec.obj_name}'. Skipping replace.")
            return None
        snap.original_poses[spec.obj_name] = original_pose
        snap.original_poses[spec.replacement_obj_name] = np.concatenate(
            [_OFFSCREEN_XYZ, _IDENTITY_QUAT])

        # Park the original first so it doesn't count as a collider
        _park_object(sim, spec.obj_name)

        target_x, target_y = original_pose[0], original_pose[1]
        original_z = original_pose[2]

        final_x, final_y, final_z, reason, self.perturbation_collision = _resolve_placement(
            sim, spec.replacement_obj_name, target_x, target_y, original_z)

        ok = _place_object_at_xyz(sim, spec.replacement_obj_name, final_x, final_y, final_z)
        if ok:
            snap.applied_poses[spec.replacement_obj_name] = \
                _read_object_pose(sim, spec.replacement_obj_name)
            msg = (f"step {spec.start_step}: REPLACE '{spec.obj_name}' "
                   f"→ '{spec.replacement_obj_name}' "
                   f"at ({final_x:.4f},{final_y:.4f},{final_z:.4f}) "
                   f"[{reason}] [reverts step {spec.end_step + 1}]")
            print(f"[TEMPORAL] {msg}")
            self._log.append(msg)
            return snap

        # Placement failed — restore original
        _write_object_pose(sim, spec.obj_name, original_pose)
        return None

    # ------------------------------------------------------------------
    # Revert
    # ------------------------------------------------------------------

    def _revert(self, sim, spec_idx: int):
        snap = self._snapshots.get(spec_idx)
        if snap is None:
            return
        spec = snap.spec

        for obj_name, original_pose in snap.original_poses.items():
            applied_pose = snap.applied_poses.get(obj_name)
            current_pose = _read_object_pose(sim, obj_name)
            if _robot_moved_object(current_pose, applied_pose, spec.robot_move_threshold_m):
                shift = (float(np.linalg.norm(current_pose[:3] - applied_pose[:3]))
                         if current_pose is not None and applied_pose is not None
                         else float("nan"))
                msg = (f"step {spec.end_step + 1}: SKIP revert '{obj_name}' "
                       f"(robot moved {shift:.4f} m > threshold {spec.robot_move_threshold_m:.4f} m)")
                print(f"[TEMPORAL] {msg}")
                self._log.append(msg)
            else:
                _write_object_pose(sim, obj_name, original_pose)
                print(f"[TEMPORAL] step {spec.end_step + 1}: REVERT pose '{obj_name}'")

        for obj_name, geom_colors in snap.original_colors.items():
            body_name = _find_object_body_name(sim, obj_name)
            if body_name:
                for gid, rgba in geom_colors.items():
                    sim.model.geom_rgba[gid] = rgba
            print(f"[TEMPORAL] step {spec.end_step + 1}: REVERT color '{obj_name}'")

        msg = (f"step {spec.end_step + 1}: REVERTED {spec.pert_type} "
               f"on '{spec.obj_name or spec.distractor_obj_name}'")
        self._log.append(msg)

    # ------------------------------------------------------------------
    # Sim access
    # ------------------------------------------------------------------

    @staticmethod
    def _get_sim(env):
        for attr_path in (("sim",), ("env", "sim")):
            obj = env
            try:
                for attr in attr_path:
                    obj = getattr(obj, attr)
                if obj is not None:
                    return obj
            except AttributeError:
                pass
        print("[TEMPORAL] WARN: Could not locate 'sim' on env.")
        return None


# ---------------------------------------------------------------------------
# BDDL helper: pre-declare hidden objects for distractor/replace
# ---------------------------------------------------------------------------

def add_hidden_objects_to_bddl(bddl_text: str, hidden_objects: List[Tuple[str, str]],
                                 target_workspace: str = "kitchen_table") -> str:
    """
    Inject objects into a BDDL that will be pre-spawned off-screen and
    teleported in/out by TemporalPerturbationManager.
    """
    OFFSCREEN_RANGES = "99.9 99.9 100.1 100.1"

    for obj_name, obj_type in hidden_objects:
        region_name = f"{obj_name}_init_region"

        obj_section = re.search(r"(\(:objects\s*\n)((?:.*\n)*?)(\s*\))", bddl_text)
        if obj_section:
            obj_content = obj_section.group(2)
            last_line = obj_content.rstrip().split('\n')[-1] if obj_content.strip() else ""
            indent = re.match(r'^(\s*)', last_line).group(1) if last_line else "    "
            new_obj_content = obj_content + f"{indent}{obj_name} - {obj_type}\n"
            bddl_text = (bddl_text[:obj_section.start()] +
                         obj_section.group(1) + new_obj_content +
                         obj_section.group(3) + bddl_text[obj_section.end():])

        region_def = (
            f"      ({region_name}\n"
            f"          (:target {target_workspace})\n"
            f"          (:ranges (\n"
            f"              ({OFFSCREEN_RANGES})\n"
            f"            )\n"
            f"          )\n"
            f"          (:yaw_rotation (\n"
            f"              (0.0 0.0)\n"
            f"            )\n"
            f"          )\n"
            f"      )"
        )

        regions_start = bddl_text.find("(:regions")
        if regions_start == -1:
            print(f"[HIDDEN] WARN: No :regions block. Skipping {obj_name}.")
            continue
        depth, regions_end = 0, -1
        for i in range(regions_start, len(bddl_text)):
            if bddl_text[i] == "(": depth += 1
            elif bddl_text[i] == ")":
                depth -= 1
                if depth == 0:
                    regions_end = i
                    break
        bddl_text = (bddl_text[:regions_end] + "\n" + region_def + "\n"
                     + bddl_text[regions_end:])

        init_section = re.search(r"(\(:init\s*\n)((?:.*\n)*?)(\s*\))", bddl_text)
        if init_section:
            init_content = init_section.group(2)
            last_line = init_content.rstrip().split('\n')[-1] if init_content.strip() else ""
            indent = re.match(r'^(\s*)', last_line).group(1) if last_line else "    "
            new_init_content = (init_content +
                                f"{indent}(On {obj_name} {target_workspace}_{region_name})\n")
            bddl_text = (bddl_text[:init_section.start()] +
                         init_section.group(1) + new_init_content +
                         init_section.group(3) + bddl_text[init_section.end():])

        print(f"[HIDDEN] Added '{obj_name}' ({obj_type}) off-screen.")
    return bddl_text


# ---------------------------------------------------------------------------
# Config-driven factory
# ---------------------------------------------------------------------------

def specs_from_config(temporal_config: List[Dict[str, Any]]) -> List[TemporalPerturbationSpec]:
    """
    Build TemporalPerturbationSpec list from a YAML config list.

    YAML structure:
        temporal_perturbations:
          - type: move
            obj_name: akita_black_bowl_1
            start_step: 50
            end_step: 150
            delta_xy: [0.06, 0.0]
            max_move_m: 0.05
            robot_move_threshold_m: 0.01   # optional, default 0.0

          - type: color
            obj_name: wine_bottle_1
            start_step: 80
            end_step: 200
            color: red                     # optional, random if omitted

          - type: distractor
            distractor_obj_name: moka_pot_999
            start_step: 100
            end_step: 300
            distractor_xy: [0.1, -0.1]    # optional, random if omitted

          - type: replace
            obj_name: wine_bottle_1
            replacement_obj_name: milk_777
            start_step: 120
            end_step: 250
    """
    specs = []
    for entry in temporal_config:
        ptype = entry["type"]
        start = entry["start_step"]
        end = entry["end_step"]
        threshold = entry.get("robot_move_threshold_m", ROBOT_MOVE_THRESHOLD_M)

        if ptype == "move":
            delta_xy = tuple(entry["delta_xy"]) if "delta_xy" in entry else None
            specs.append(TemporalPerturbationSpec(
                pert_type="move",
                start_step=start, end_step=end,
                obj_name=entry["obj_name"],
                delta_xy=delta_xy,
                max_move_m=entry.get("max_move_m", 0.05),
                robot_move_threshold_m=threshold,
            ))
        elif ptype == "color":
            specs.append(TemporalPerturbationSpec(
                pert_type="color",
                start_step=start, end_step=end,
                obj_name=entry["obj_name"],
                color=entry.get("color"),
            ))
        elif ptype == "distractor":
            dxy = tuple(entry["distractor_xy"]) if "distractor_xy" in entry else None
            specs.append(TemporalPerturbationSpec(
                pert_type="distractor",
                start_step=start, end_step=end,
                distractor_obj_name=entry["distractor_obj_name"],
                distractor_xy=dxy,
                robot_move_threshold_m=threshold,
            ))
        elif ptype == "replace":
            specs.append(TemporalPerturbationSpec(
                pert_type="replace",
                start_step=start, end_step=end,
                obj_name=entry["obj_name"],
                replacement_obj_name=entry["replacement_obj_name"],
                robot_move_threshold_m=threshold,
            ))
        else:
            raise ValueError(f"Unknown temporal perturbation type: '{ptype}'")
    return specs